#!/bin/bash

cat >/etc/init/v2ray.conf <<EOL
description     "v2ray"
author          "v2ray <example@gmail.com>"

start on runlevel [2345]
stop on runlevel [!2345]

respawn
# normal exit -9999

env OPTS="-config /etc/v2ray/config.json"

script
    exec /usr/bin/v2ray/v2ray $OPTS
end script
EOL

initctl start v2ray
